---
server:
 port: 4474
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/swaahire/pluralsight-spring-cloudcofig.git
          
          search-paths:
          - 'station*'